config/routes.rb
DMPonline4::Application.routes.draw do
  
    
  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => 'confirmations', :passwords => 'passwords', :sessions => 'sessions', :omniauth_callbacks => 'users/omniauth_callbacks'} do
  	get "/users/sign_out", :to => "devise/sessions#destroy"
  end 
  resources :contacts, :controllers => {:contacts => 'contacts'}
  
  get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  
  root :to => 'home#index'

  ActiveAdmin.routes(self)
  
  get "about_us" => 'static_pages#about_us', :as => "about_us"
  get "help" => 'static_pages#help', :as => "help"
  get "roadmap" => 'static_pages#roadmap', :as => "roadmap"
  get "terms" => 'static_pages#termsuse', :as => "terms"
  get "existing_users" => 'existing_users#index', :as => "existing_users"
  
  get "org/admin/users" => 'organisation_users#admin_index', :as => "org/admin/users"
 
 	resources :organisations, :path => 'org/admin' do
  	member do
			get 'children'
			get 'templates'
			get 'admin_show'
			get 'admin_edit'
			put 'admin_update'
		end
	end
 
 	resources :guidances, :path => 'org/admin/guidance' do
  	member do
  		get 'admin_show'
  		get 'admin_index'
			get 'admin_edit'
			get 'admin_new'
			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
			
			get 'update_phases', :as => 'update_phases'
  		get 'update_versions', :as => 'update_versions'
  		get 'update_sections', :as => 'update_sections'
  		get 'update_questions', :as => 'update_questions'
   	end
  end
 
 	resources :guidance_groups, :path => 'org/admin/guidancegroup' do
 		member do
 			get 'admin_show'
 			get 'admin_new'
 			get 'admin_edit'
 			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
  	end
  end
 
 	resource :organisation 
 
  
  resources :dmptemplates, :path => 'org/admin/templates' do
 		member do
 			get 'admin_index'
 			get 'admin_template'
			get 'admin_new'
			get 'admin_addphase'
			get 'admin_phase'
			get 'admin_previewphase'
			get 'admin_cloneversion'
			delete 'admin_destroy' 
			delete 'admin_destroyversion'
			delete 'admin_destroyphase'
			delete 'admin_destroysection'
			delete 'admin_destroyquestion'
			delete 'admin_destroysuggestedanswer'
			post 'admin_create'
			post 'admin_createphase'
			post 'admin_createsection'
			post 'admin_createquestion'
			post 'admin_createsuggestedanswer'
			put 'admin_update'
			put 'admin_updatephase'
			put 'admin_updateversion'
			put 'admin_updatesection'
			put 'admin_updatequestion'
			put 'admin_updatesuggestedanswer'
  	end
  end
   
  resources :phases
  resources :versions
  resources :sections
  resources :questions
  resources :question_themes

  
  resources :themes
  
  resources :answers
  resources :plan_sections
  resources :comments do
    member do
        put 'archive'
    end
  end
  
  resources :projects do
  	resources :plans do
		member do
			get 'status'
			get 'locked'
			get 'answer'
            get 'edit'
			post 'delete_recent_locks'
			post 'lock_section'
			post 'unlock_section'
			post 'unlock_all_sections'
			get 'export'
			get 'warning'
			get 'section_answers'
		end
	end
	
	member do
		get 'share'
		get 'export'
		post 'invite'
		post 'create'
	end
	collection do
		get 'possible_templates'
		get 'possible_guidance'
	end
  end
  
    
  resources :project_partners
  resources :project_groups

  resources :users
  resources :user_statuses
  resources :user_types
  
  resources :user_role_types
  resources :user_org_roles
  
  
  resources :organisation_types
  resources :pages
 
  resources :file_types
  resources :file_uploads

  namespace :settings do
    resource :projects
    resources :plans
  end
  

end

app/models/guidance.rb
# [+Project:+] DMPonline v4
# [+Description:+] 
#   This class keeps the information organisations enter to support users when answering questions. 
#   It always belongs to a guidance group class and it can be linked directly to a question or through one or more themes
# [+Created:+] 07/07/2014
# [+Copyright:+] Digital Curation Centre 



class Guidance < ActiveRecord::Base
   #associations between tables
	attr_accessible :text, :question_id
    attr_accessible :guidance_group_ids
    attr_accessible :theme_ids
   
    belongs_to :question
	
    #belongs_to :dmptemplate
	#belongs_to :theme
	
    has_and_belongs_to_many :guidance_groups, join_table: "guidance_in_group"
	has_and_belongs_to_many :themes, join_table: "themes_in_guidance"
  
    accepts_nested_attributes_for :themes
    accepts_nested_attributes_for :guidance_groups
  
 
	#verifies if one guidance belongs to a org
	def in_group_belonging_to?(organisation_id)
		guidance_groups.each do |guidance_group|
			if guidance_group.organisation_id == organisation_id then
				return true
			end
		end
		return false
	end
	
	
	#all guidance that belong to an organisation
	def self.by_organisation(org_id)
		all_guidance = Guidance.all
		org_guidance = Array.new
    
		all_guidance.each do |guidance|
		   if guidance.in_group_belonging_to?(org_id) then
				org_guidance << guidance
		   end
		end
		
		return org_guidance
		
	end
	
	
	def get_guidance_group_templates? (guidance_group)
			templates = guidancegroups.where("guidance_group_id (?)", guidance_group.id).template 
			return templates
		end
			
	
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base

	#associations between tables
	belongs_to :organisation_type
	has_many :guidance_groups
    has_many :dmptemplates
	has_many :sections
	has_many :users
	has_many :option_warnings
	has_many :suggested_answers
    
    has_many :user_org_roles
	
    belongs_to :parent, :class_name => 'Organisation'
	has_many :children, :class_name => 'Organisation', :foreign_key => 'parent_id'

	accepts_nested_attributes_for :organisation_type
	accepts_nested_attributes_for :dmptemplates

	attr_accessible :abbreviation, :banner_text, :description, :domain, :logo_file_name, :name, :stylesheet_file_id, :target_url, :organisation_type_id, :wayfless_entity, :parent_id, :sort_name

	def to_s
		name
	end

	def short_name
		if abbreviation.nil? then
			return name
		else
			return abbreviation
		end
	end

	#retrieves info off a child org
	def self.orgs_with_parent_of_type(org_type)
		parents = OrganisationType.find_by_name(org_type).organisations
		children = Array.new
		parents.each do |parent|
		  	children += parent.children
		end
		return children
	end


	def self.other_organisations
		org_types = [I18n.t('helpers.org_type.organisation')]
		organisations_list = []
		org_types.each do |ot|
			new_org_obejct = OrganisationType.find_by_name(ot)

			org_with_guidance = GuidanceGroup.joins(new_org_obejct.organisations)

			organisations_list = organisations_list + org_with_guidance
		end
		return organisations_list
	end

	def all_sections(version_id)
		if parent.nil?
			secs = sections.where("version_id = ?", version_id)
			if secs.nil? then
				secs = Array.new
			end
			return secs
		else
			return sections.find_all_by_version_id(version_id) + parent.all_sections(version_id)
		end
	end

	def all_guidance_groups
		ggs = guidance_groups
		children.each do |c|
			ggs = ggs + c.all_guidance_groups
		end
		return ggs
	end

	def root
		if parent.nil?
			return self
		else
			return parent.root
		end
	end

	def warning(option_id)
		warning = option_warnings.find_by_option_id(option_id)
		if warning.nil? && !parent.nil? then
			return parent.warning(option_id)
		else
			return warning
		end
	end

	def published_templates
		return dmptemplates.find_all_by_published(1)
	end


end

app/controllers/guidances_controller.rb
class GuidancesController < ApplicationController

  # GET /guidances
  # GET /guidances.json
  def admin_index
    if user_signed_in? && current_user.is_org_admin? then
	    @guidances = Guidance.by_organisation(current_user.organisation_id)
	    @guidance_groups = GuidanceGroup.where('organisation_id = ?', current_user.organisation_id )


	    respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @guidances }
	    end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end

  # GET /guidances/1
  # GET /guidances/1.json
  def admin_show
    if user_signed_in? && current_user.is_org_admin? then
	    @guidance = Guidance.find(params[:id])

	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @guidance }
	    end
   end
  end

  def admin_new
    if user_signed_in? && current_user.is_org_admin? then
	    @guidance = Guidance.new
			@dmptemplates = Dmptemplate.funders_and_own_templates(current_user.organisation_id)
			@phases = nil
			@dmptemplates.each do |template|
				if @phases.nil? then
					@phases = template.phases.find(:all,:order => 'number ASC')
				else
					@phases = @phases + template.phases.find(:all,:order => 'number ASC')
				end
			end
			@versions = nil
			@phases.each do |phase|
				if @versions.nil? then
					@versions = phase.versions.find(:all,:order => 'title ASC')
				else
					@versions = @versions + phase.versions.find(:all,:order => 'title ASC')
				end
			end
			@sections = nil
			@versions.each do |version|
				if @sections.nil? then
					@sections = version.sections.find(:all,:order => 'number ASC')
				else
					@sections = @sections + version.sections.find(:all,:order => 'number ASC')
				end
			end
			@questions = nil
			@sections.each do |section|
				if @questions.nil? then
					@questions = section.questions.find(:all,:order => 'number ASC')
				else
					@questions = @questions + section.questions.find(:all,:order => 'number ASC')
				end
			end
	    respond_to do |format|
	      format.html
	    end
   	end
	end

	#setup variables for use in the dynamic updating
	def update_phases
    # updates phases, versions, sections and questions based on template selected
    dmptemplate = Dmptemplate.find(params[:dmptemplate_id])
    # map to title and id for use in our options_for_select
    @phases = dmptemplate.phases.map{|a| [a.title, a.id]}.insert(0, "Select a phase")
    @versions = dmptemplate.versions.map{|s| [s.title, s.id]}.insert(0, "Select a version")
    @sections = dmptemplate.sections.map{|s| [s.title, s.id]}.insert(0, "Select a section")
    @questions = dmptemplate.questions.map{|s| [s.text, s.id]}.insert(0, "Select a question")

  end

 def update_versions
    # updates versions, sections and questions based on phase selected
    phase = Phase.find(params[:phase_id])
    # map to name and id for use in our options_for_select
    @versions = phase.versions.map{|s| [s.title, s.id]}.insert(0, "Select a version")
    @sections = phase.sections.map{|s| [s.title, s.id]}.insert(0, "Select a section")
    @questions = phase.questions.map{|s| [s.text, s.id]}.insert(0, "Select a question")
  end

  def update_sections
    # updates sections and questions based on version selected
    version = Version.find(params[:version_id])
    # map to name and id for use in our options_for_select
    @sections = version.sections.map{|s| [s.title, s.id]}.insert(0, "Select a section")
    @questions = version.questions.map{|s| [s.text, s.id]}.insert(0, "Select a question")
  end

  def update_questions
    # updates songs based on artist selected
    section = Section.find(params[:section_id])
    @questions = section.questions.map{|s| [s.text, s.id]}.insert(0, "Select a question")
  end


  # GET /guidances/1/edit
  def admin_edit
  	if user_signed_in? && current_user.is_org_admin? then
      @guidance = Guidance.find(params[:id])
      @dmptemplates = Dmptemplate.funders_and_own_templates(current_user.organisation_id)
			@phases = nil
			@dmptemplates.each do |template|
				if @phases.nil? then
					@phases = template.phases.find(:all,:order => 'number ASC')
				else
					@phases = @phases + template.phases.find(:all,:order => 'number ASC')
				end
			end
			@versions = nil
			@phases.each do |phase|
				if @versions.nil? then
					@versions = phase.versions.find(:all,:order => 'title ASC')
				else
					@versions = @versions + phase.versions.find(:all,:order => 'title ASC')
				end
			end
			@sections = nil
			@versions.each do |version|
				if @sections.nil? then
					@sections = version.sections.find(:all,:order => 'number ASC')
				else
					@sections = @sections + version.sections.find(:all,:order => 'number ASC')
				end
			end
			@questions = nil
			@sections.each do |section|
				if @questions.nil? then
					@questions = section.questions.find(:all,:order => 'number ASC')
				else
					@questions = @questions + section.questions.find(:all,:order => 'number ASC')
				end
			end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end

  # POST /guidances
  # POST /guidances.json
  def admin_create
    if user_signed_in? && current_user.is_org_admin? then
	    @guidance = Guidance.new(params[:guidance])
	    @guidance.text = params["guidance-text"]
	    @guidance.question_id = params["question_id"]

	    respond_to do |format|
	      if @guidance.save
	        format.html { redirect_to admin_show_guidance_path(@guidance), notice: I18n.t('org_admin.guidance.created_message') }
	        format.json { render json: @guidance, status: :created, location: @guidance }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @guidance.errors, status: :unprocessable_entity }
	      end
	    end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end

  # PUT /guidances/1
  # PUT /guidances/1.json
  def admin_update
 		if user_signed_in? && current_user.is_org_admin? then
   		@guidance = Guidance.find(params[:id])

			@guidance.text = params["guidance-text"]

			@guidance.question_id = params["question_id"]

	    respond_to do |format|
	      if @guidance.update_attributes(params[:guidance])
	        format.html { redirect_to admin_show_guidance_path(params[:guidance]), notice: I18n.t('org_admin.guidance.updated_message') }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @guidance.errors, status: :unprocessable_entity }
	      end
	    end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end


  # DELETE /guidances/1
  # DELETE /guidances/1.json
  def admin_destroy
  	if user_signed_in? && current_user.is_org_admin? then
	   	@guidance = Guidance.find(params[:id])
	    @guidance.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_index_guidance_path }
	      format.json { head :no_content }
	    end
	 	else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end

	end



end

app/views/guidances/admin_index.html.erb
<%= stylesheet_link_tag "admin" %>
<% javascript 'admin.js' %>


<h1>
	<%= t('org_admin.guidance_group.guidance_group_list') %>
</h1>

<div class="div_left">
	<%= raw t('org_admin.guidance_group.guidance_group_text_html')%>
</div>
<div class="div_right">
	<div class="move_2_right">
		<%= link_to t("org_admin.guidance_group.add_guidance_group"), admin_new_guidance_group_path(), :class => 'btn btn-primary' %>
	</div>
</div>
	
<!-- List of guidance groups -->
<% if @guidance_groups.count > 0 then%>	
	<table id="dmp_table_2" class="dmp_table tablesorter">
	  <thead>
	    <tr>
	      	<th class="dmp_th_medium"><%= t('org_admin.guidance_group.name_label') %></th>
			<th class="dmp_th_medium"><%= t('org_admin.guidance.template') %></th>
			<th class="dmp_th_small"><%= t('org_admin.guidance_group.subset') %></th>
	      	<th class="dmp_th_small"><%= t('org_admin.guidance.last_updated') %></th>
	      	<td class="dmp_th_medium"><%= t('org_admin.guidance.actions') %></td>
	    </tr>
	  </thead>
	  <tbody>
	  	<% !@guidance_groups.each do |guidance_gr| %>
	  		<tr>
		        <td class="dmp_td_medium">
		        	<%= guidance_gr.name %>
		        </td>
		        <% guidance_group_temp = guidance_gr.dmptemplate_ids %>
		        <% if guidance_group_temp != [] then %>
		        	<td class="dmp_td_medium">
		        		<% i = 1 %>
			        	<% guidance_group_temp.each do |t| %>
			        		<% temp = Dmptemplate.find(t) %>
			             	<%= temp.title %>
			             	
			        		<% if guidance_group_temp.count > i then%> 
								,	
								<% i +=1 %>		
							<% end %>
				   		<%end%>
				   	</td>	     
				<%else%>
				    <td class="dmp_td_medium">
				       	<%= t('org_admin.guidance_group.all_temp')%>
				    </td>
				<%end%>	 
				<td class="dmp_td_small">
					<%if guidance_gr.optional_subset.nil? || guidance_gr.optional_subset == false then%>
						<%= t('helpers.no')%>
					<%else%>
						<%= t('helpers.yes')%>	
					<%end%>
				</td>
			    	
		        <td class="dmp_td_small">
		        	<%= l guidance_gr.updated_at.to_date, :formats => :short %>
		        </td>
		        <td class="dmp_td_medium">
		        	<%= link_to t("helpers.view"), admin_show_guidance_group_path(guidance_gr), :class => "dmp_table_link"%>
					<%= link_to t("helpers.submit.edit"), admin_edit_guidance_group_path(guidance_gr), :class => "dmp_table_link"%>
					<%= link_to t("helpers.submit.delete"), admin_destroy_guidance_group_path(guidance_gr),
						:confirm => t("org_admin.guidance_group.delete_message", :guidance_group_name => guidance_gr.name ), :method => :delete, :class => "dmp_table_link"%>
		        </td>
		      </tr>
		   
	    <%end%>
	  </tbody>
	</table>
<%end%>	

<br/>
<div class="div_clear"></div>

<h1>
	<%= t('org_admin.guidance.guidance_list') %>           
</h1>

<div class="div_left">
	<%= raw t('org_admin.guidance.guidance_text_html')%>
</div>
<div class="div_right">
	<!-- link button to add new guidance -->
	<div class="move_2_right">
		<%= link_to t("org_admin.guidance.add_guidance"),
		            admin_new_guidance_path(),
		            :class => 'btn btn-primary' %>
	</div> 
</div>

<div class="div_clear"></div>

<!-- List of guidance -->
<% if @guidances.count > 0 then%>	
	<table id="dmp_table" class="dmp_table tablesorter">
	  <thead>
	    <tr>
	      	<th class="dmp_th_big"><%= t('org_admin.guidance.text_label') %></th>
	      	<th class="dmp_th_small"><%= t('org_admin.guidance.theme_label') %></th>
	      	<th class="dmp_th_small"><%= t('org_admin.guidance.question') %></th>
	      	<th class="dmp_th_small"><%= t('org_admin.guidance.guidance_group_label') %></th>
			<th class="dmp_th_small"><%= t('org_admin.guidance.last_updated') %></th>
	      	<td class="dmp_th_medium"><%= t('org_admin.guidance.actions') %></td>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @guidances.each do |guidance| %>
	  		<% if guidance.in_group_belonging_to?(current_user.organisation_id) then %>
		      <tr>
		        <td class="dmp_td_big">
		        	<%= guidance.text.html_safe%>
		        </td>
		        <% if guidance.themes != [] then %>
			        <td class="dmp_td_small">
			        	<% guidance.themes.each do |th| %>
			        		<%= th.title %>
			        	<%end%>	
			        </td>
			    <%else%>
			    	<td class="dmp_td_small">
			        	-
			        </td>
			    <%end%>
			    <% if !guidance.question_id.nil? then %>
			        <td class="dmp_td_small">
			        	<%= raw guidance.question.text.truncate(70, omission: '... (continued)') %>
			        </td>
			    <%else%>
			    	<td class="dmp_td_small">
			        	-
			        </td>
			    <%end%>
			    <% if guidance.guidance_groups != [] then %>    
			        <td class="dmp_td_small">
			        	<% guidance.guidance_groups.each do |p|%>
							<%= p.name %>
						<%end%>
			        </td>
		        <%else%>
			    	<td class="dmp_td_small">
			        	-
			        </td>
			    <%end%>
		        <td class="dmp_td_small">
		        	<%= l guidance.updated_at.to_date, :formats => :short %>
		        </td>
		        <td class="dmp_td_medium">
		        	<%= link_to t("helpers.view"), admin_show_guidance_path(guidance), :class => "dmp_table_link"%><br/>
					<%= link_to t("helpers.submit.edit"), admin_edit_guidance_path(guidance), :class => "dmp_table_link"%><br/>
					<%= link_to t("helpers.submit.delete"), admin_destroy_guidance_path(guidance),
						:confirm => t("org_admin.guidance.delete_message_html", :guidance_summary => truncate(sanitize(guidance.text,:tags => %w(br a)), :length => 20 , :omission => "...(continued)") ), :method => :delete, :class => "dmp_table_link"%>
		        </td>
		      </tr>
		    <%end%>
	    <%end%>
	  </tbody>
	</table>
<%end%>	

app/views/guidances/admin_show.html.erb
<%= stylesheet_link_tag "admin" %>

<h1>
	<%= t('org_admin.guidance_label') %>

	<!-- link button to add new guidance -->
	<div class="move_2_right">
		<%= link_to t("org_admin.guidance.add_guidance"),
		            admin_new_guidance_path(),
		            :class => 'btn btn-primary' %>
		<%= link_to t("org_admin.guidance.view_all_guidance"),
		            admin_index_guidance_path,
		            :class => 'btn btn-primary' %>
	</div>            
</h1>

<div class="div_clear"></div>

<div class="white_background blue_border">
	<!-- body -->
	<div class="dmp_details">
		
		<table class="dmp_details_table">
			<tr>
				<td class="first"><%= t('org_admin.guidance.text_label') %></td>
				<td><%= raw @guidance.text %></td>
			</tr>
			<% if @guidance.themes !=[] then %>
				<tr>
					<td class="first"><%= t('org_admin.guidance.themes_label') %></td>
					<td><% @guidance.themes.each do |th|%>
							<%= th.title %>
						<%end%>
					</td>
				</tr>
			<%end%>	
			<% if !@guidance.question_id.nil? %>
				<tr>
					<td class="first"><%= t('org_admin.guidance.question_label') %></td>
					<td><%= raw @guidance.question.text %></td>
				</tr>
			<%end%>	
			<tr>
				<td class="first"><%= t('org_admin.guidance.guidance_group_label') %></td>
				<td><% @guidance.guidance_groups.each do |p|%>
						<%= p.name %>
					<%end%>
				</td>
			</tr>
			<tr>
				<td class="first"><%= t('org_admin.guidance.created') %></td>
				<td><%= l @guidance.created_at.to_date, :formats => :short %></td>
			</tr>
			<tr>
				<td class="first"><%= t('org_admin.guidance.last_updated') %></td>
				<td><%= l @guidance.updated_at.to_date, :formats => :short %></td>
			</tr>
			
		</table>
		<div class="move_2_right">
			<%= link_to t('helpers.submit.edit'), admin_edit_guidance_path(@guidance.id), :class => 'btn btn-primary'%>
			<%= link_to t('helpers.submit.back'), :back, :class => 'btn cancel' %>
		</div>
		<br />
	</div>
</div>	

app/views/guidances/update_phases.js.erb
$('#phases_select').html("<%= escape_javascript(options_for_select(@phases)) %>");
$('#versions_select').html("<%= escape_javascript(options_for_select(@versions)) %>");
$('#sections_select').html("<%= escape_javascript(options_for_select(@sections)) %>");
$('#questions_select').html("<%= escape_javascript(options_for_select(@questions)) %>");
 

app/views/guidances/update_questions.js.erb
$('#questions_select').html("<%= escape_javascript(options_for_select(@questions)) %>hiya");

app/views/guidances/update_sections.js.erb
$('#sections_select').html("<%= escape_javascript(options_for_select(@sections)) %>");
$('#questions_select').html("<%= escape_javascript(options_for_select(@questions)) %>");

app/views/guidances/update_versions.js.erb
$('#versions_select').html("<%= escape_javascript(options_for_select(@versions)) %>");
$('#sections_select').html("<%= escape_javascript(options_for_select(@sections)) %>");
$('#questions_select').html("<%= escape_javascript(options_for_select(@questions)) %>");