config/routes.rb
DMPonline4::Application.routes.draw do
  
    
  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => 'confirmations', :passwords => 'passwords', :sessions => 'sessions', :omniauth_callbacks => 'users/omniauth_callbacks'} do
  	get "/users/sign_out", :to => "devise/sessions#destroy"
  end 
  resources :contacts, :controllers => {:contacts => 'contacts'}
  
  get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  
  root :to => 'home#index'

  ActiveAdmin.routes(self)
  
  get "about_us" => 'static_pages#about_us', :as => "about_us"
  get "help" => 'static_pages#help', :as => "help"
  get "roadmap" => 'static_pages#roadmap', :as => "roadmap"
  get "terms" => 'static_pages#termsuse', :as => "terms"
  get "existing_users" => 'existing_users#index', :as => "existing_users"
  
  get "org/admin/users" => 'organisation_users#admin_index', :as => "org/admin/users"
 
 	resources :organisations, :path => 'org/admin' do
  	member do
			get 'children'
			get 'templates'
			get 'admin_show'
			get 'admin_edit'
			put 'admin_update'
		end
	end
 
 	resources :guidances, :path => 'org/admin/guidance' do
  	member do
  		get 'admin_show'
  		get 'admin_index'
			get 'admin_edit'
			get 'admin_new'
			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
			
			get 'update_phases', :as => 'update_phases'
  		get 'update_versions', :as => 'update_versions'
  		get 'update_sections', :as => 'update_sections'
  		get 'update_questions', :as => 'update_questions'
   	end
  end
 
 	resources :guidance_groups, :path => 'org/admin/guidancegroup' do
 		member do
 			get 'admin_show'
 			get 'admin_new'
 			get 'admin_edit'
 			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
  	end
  end
 
 	resource :organisation 
 
  
  resources :dmptemplates, :path => 'org/admin/templates' do
 		member do
 			get 'admin_index'
 			get 'admin_template'
			get 'admin_new'
			get 'admin_addphase'
			get 'admin_phase'
			get 'admin_previewphase'
			get 'admin_cloneversion'
			delete 'admin_destroy' 
			delete 'admin_destroyversion'
			delete 'admin_destroyphase'
			delete 'admin_destroysection'
			delete 'admin_destroyquestion'
			delete 'admin_destroysuggestedanswer'
			post 'admin_create'
			post 'admin_createphase'
			post 'admin_createsection'
			post 'admin_createquestion'
			post 'admin_createsuggestedanswer'
			put 'admin_update'
			put 'admin_updatephase'
			put 'admin_updateversion'
			put 'admin_updatesection'
			put 'admin_updatequestion'
			put 'admin_updatesuggestedanswer'
  	end
  end
   
  resources :phases
  resources :versions
  resources :sections
  resources :questions
  resources :question_themes

  
  resources :themes
  
  resources :answers
  resources :plan_sections
  resources :comments do
    member do
        put 'archive'
    end
  end
  
  resources :projects do
  	resources :plans do
		member do
			get 'status'
			get 'locked'
			get 'answer'
            get 'edit'
			post 'delete_recent_locks'
			post 'lock_section'
			post 'unlock_section'
			post 'unlock_all_sections'
			get 'export'
			get 'warning'
			get 'section_answers'
		end
	end
	
	member do
		get 'share'
		get 'export'
		post 'invite'
		post 'create'
	end
	collection do
		get 'possible_templates'
		get 'possible_guidance'
	end
  end
  
    
  resources :project_partners
  resources :project_groups

  resources :users
  resources :user_statuses
  resources :user_types
  
  resources :user_role_types
  resources :user_org_roles
  
  
  resources :organisation_types
  resources :pages
 
  resources :file_types
  resources :file_uploads

  namespace :settings do
    resource :projects
    resources :plans
  end
  

end

app/models/dmptemplate.rb
class Dmptemplate < ActiveRecord::Base
    
    attr_accessible :organisation_id, :description, :published, :title, :user_id, :locale, :is_default, :guidance_group_ids 
  
    #associations between tables
    has_many :phases
    has_many :versions, :through => :phases
    has_many :sections, :through => :versions
    has_many :questions, :through => :sections
    has_many :projects
    
    #has_many :guidances                needs to be removed and checked
    
    belongs_to :organisation
      
	has_and_belongs_to_many :guidance_groups, join_table: "dmptemplates_guidance_groups"
	
    accepts_nested_attributes_for :guidance_groups
    accepts_nested_attributes_for :phases
    accepts_nested_attributes_for :organisation
    accepts_nested_attributes_for :projects

    
  has_settings :export, class_name: 'Settings::Dmptemplate' do |s|
    s.key :export, defaults: Settings::Dmptemplate::DEFAULT_SETTINGS
  end
    
  def to_s
    "#{title}"
  end
  
  def self.templates_org_type(ot)
    new_org_obejcts = OrganisationType.find_by_name(ot).organisations
    
    org_templates = Array.new
    new_org_obejcts.each do |neworg|
       org_templates += neworg.dmptemplates.where("published = ?", true)
    end
    
    return org_templates
  end 

	#returns all funders templates
	def self.funders_templates
		new_org_obejcts = OrganisationType.find_by_name(I18n.t("helpers.org_type.funder")).organisations
	  org_templates = Array.new
   	
   	new_org_obejcts.each do |neworg|
       	org_templates += neworg.dmptemplates
    end
    
    return org_templates	
	end
	
	
	#returns all institutional templates bellowing to the current user's org
	def self.own_institutional_templates(org_id)
		new_templates = self.where("organisation_id = ?", org_id)
		return new_templates
	end
	
	#returns an array with all funders and own institutional templates
	def self.funders_and_own_templates(org_id)
		funders_templates = self.funders_templates
	
        #verify if org type is not a funder
        current_org = Organisation.find(org_id)
        if current_org.organisation_type.name != I18n.t("helpers.org_type.funder") then 
            own_institutional_templates = self.own_institutional_templates(org_id)
		else
            own_institutional_templates = []
        end    
            
		templates_list = Array.new
		templates_list += own_institutional_templates
		templates_list += funders_templates
		templates_list = templates_list.sort_by { |f| f['title'].downcase }
				
		return templates_list
	end
	
	def org_type
		org_type = organisation.organisation_type.name
		return org_type
	end
	
	#verify if a template has customisation by current user's org
	def has_customisations?(org_id, temp)
		if temp.organisation_id != org_id then
			temp.phases.each do |phase|
				phase.versions.each do |version|
					version.sections.each do |section|
						return true if section.organisation_id == org_id 
											
					end	
				end
				return false 
			end
		else
			return false 	
		end	
	end
	
	
	# verify if there are any publish version for the template
	def has_published_versions?
		phases.each do |phase|
			return true if !phase.latest_published_version.nil?
		end
		return false 
	end

end

app/controllers/dmptemplates_controller.rb
# [+Project:+] DMPonline v4
# [+Description:+] This controller is responsible for all the actions in the admin interface under templates (e.g. phases, versions, sections, questions, suggested answer) (index; show; create; edit; delete)
# [+Copyright:+] Digital Curation Centre 

class DmptemplatesController < ApplicationController

  # GET /dmptemplates
  # GET /dmptemplates.json
  def admin_index
    if user_signed_in? && current_user.is_org_admin? then
    	#institutional templates
	    @dmptemplates_own = Dmptemplate.own_institutional_templates(current_user.organisation_id)

	    #funders templates
	    @dmptemplates_funders = Dmptemplate.funders_templates

     respond_to do |format|
	      format.html # index.html.erb
	   end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end

  # GET /dmptemplates/1
  # GET /dmptemplates/1.json
  def admin_template
    if user_signed_in? && current_user.is_org_admin? then
	    @dmptemplate = Dmptemplate.find(params[:id])

	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @dmptemplate }
	    end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end



  # PUT /dmptemplates/1
  # PUT /dmptemplates/1.json
  def admin_update
 	if user_signed_in? && current_user.is_org_admin? then
   		@dmptemplate = Dmptemplate.find(params[:id])
   		@dmptemplate.description = params["template-desc"]

 		  respond_to do |format|
	      if @dmptemplate.update_attributes(params[:dmptemplate])
	        format.html { redirect_to admin_template_dmptemplate_path(params[:dmptemplate]), notice: I18n.t('org_admin.templates.updated_message') }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @dmptemplate.errors, status: :unprocessable_entity }
	      end
	  	end
  	else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
	end
  end


    # GET /dmptemplates/new
  # GET /dmptemplates/new.json
  def admin_new
    if user_signed_in? && current_user.is_org_admin? then
	    @dmptemplate = Dmptemplate.new

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @dmptemplate }
	    end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end

  # POST /dmptemplates
  # POST /dmptemplates.json
  def admin_create
    if user_signed_in? && current_user.is_org_admin? then
	    @dmptemplate = Dmptemplate.new(params[:dmptemplate])
	    @dmptemplate.organisation_id = current_user.organisation.id
	    @dmptemplate.description = params['template-desc']

	    respond_to do |format|
	      if @dmptemplate.save
	        format.html { redirect_to admin_template_dmptemplate_path(@dmptemplate), notice: I18n.t('org_admin.templates.created_message') }
	        format.json { render json: @dmptemplate, status: :created, location: @dmptemplate }
	      else
	        format.html { render action: "admin_new" }
	        format.json { render json: @dmptemplate.errors, status: :unprocessable_entity }
	      end
	    end
    else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
  end



  # DELETE /dmptemplates/1
  # DELETE /dmptemplates/1.json
  def admin_destroy
  	if user_signed_in? && current_user.is_org_admin? then
	   	@dmptemplate = Dmptemplate.find(params[:id])
	    @dmptemplate.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_index_dmptemplate_path }
	      format.json { head :no_content }
	    end
	 	else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
	end



	# PHASES

	#show and edit a phase of the template
	def admin_phase
		if user_signed_in? && current_user.is_org_admin? then

			@phase = Phase.find(params[:id])

			if !params.has_key?(:version_id) then
				@edit = 'false'
				#check for the most recent published version, if none is available then return the most recent one
				versions = @phase.versions.where('published = ?', true).order('updated_at DESC')
				if versions.any?() then
					@version = versions.first
				else
					@version = @phase.versions.order('updated_at DESC').first
				end
				# When the version_id is passed as an argument
			else
				@edit = params[:edit]
				@version = Version.find(params[:version_id])
			end

			#verify if there are any sections if not create one
			@sections = @version.sections
			if !@sections.any?() || @sections.count == 0 then
				@section = @version.sections.build
				@section.title = ''
				@section.version_id = params[:version_id]
				@section.number = 1
				@section.organisation_id = current_user.organisation.id
				@section.published = true
				@section.save
			end

			#verify if section_id has been passed, if so then open that section
			if params.has_key?(:section_id) then
				@open = true
				@section_id = params[:section_id].to_i
			end

			if params.has_key?(:question_id) then
				@question_id = params[:question_id].to_i
			end

			respond_to do |format|
				format.html
			end
		end
	end
	
	#preview a phase
	def admin_previewphase
		if user_signed_in? && current_user.is_org_admin? then
			
			@version = Version.find(params[:id])
			
				
			respond_to do |format|
				format.html
			end
		end	
	end


	#add a new phase to a template
	def admin_addphase
		if user_signed_in? && current_user.is_org_admin? then
			@dmptemplate = Dmptemplate.find(params[:id])
			@phase = Phase.new
			if @dmptemplate.phases.count == 0 then
				@phase.number = '1'
			else
				@phase.number = @dmptemplate.phases.count + 1
			end

			respond_to do |format|
              format.html
            end
		end
	end

	#create a phase
	def admin_createphase
    if user_signed_in? && current_user.is_org_admin? then
	 	@phase = Phase.new(params[:phase])
	    @phase.description = params["phase-desc"]
	    @version = @phase.versions.build
	    @version.title = "#{@phase.title} v.1"
	    @version.phase_id = @phase.id
	    @version.number = 1
	    @version.published = false

	    respond_to do |format|
	      if @phase.save
	        format.html { redirect_to admin_phase_dmptemplate_path(:id => @phase.id, :version_id => @version.id, :edit => 'true'), notice: I18n.t('org_admin.templates.created_message') }
         	format.json { head :no_content }
	      else
	        format.html { render action: "admin_phase" }
	        format.json { render json: @phase.errors, status: :unprocessable_entity }
	      end
			end
		end
  end


	#update a phase of a template
	def admin_updatephase
		if user_signed_in? && current_user.is_org_admin? then
   		@phase = Phase.find(params[:id])
		@phase.description = params["phase-desc"]

	    respond_to do |format|
	      if @phase.update_attributes(params[:phase])
	        format.html { redirect_to admin_phase_dmptemplate_path(@phase), notice: I18n.t('org_admin.templates.updated_message') }
	        format.json { head :no_content }
	      else
	        format.html { render action: "admin_phase" }
	        format.json { render json: @phase.errors, status: :unprocessable_entity }
	      end
	    end
		end
	end

	#delete a version, sections and questions
	def admin_destroyphase
  	if user_signed_in? && current_user.is_org_admin? then
	   	@phase = Phase.find(params[:phase_id])
	   	@dmptemplate = @phase.dmptemplate
	    @phase.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_template_dmptemplate_path(@dmptemplate), notice: I18n.t('org_admin.templates.destroyed_message') }
	      format.json { head :no_content }
	    end
	 	end
	end

# VERSIONS

	#update a version of a template
	def admin_updateversion
		if user_signed_in? && current_user.is_org_admin? then
	   		@version = Version.find(params[:id])
            @version.description = params["version-desc"]
            @phase = @version.phase

            if @version.published && !@phase.dmptemplate.published then
                @phase.dmptemplate.published = true
            end
            
            @all_versions = @phase.versions.where('published = ?', true)
            @all_versions.each do |v|
                if v.id != @version.id && v.published == true then
                    v.published = false
                    v.save
                end
            end

		    respond_to do |format|
		      if @version.update_attributes(params[:version])
		        format.html { redirect_to admin_phase_dmptemplate_path(@phase, :version_id =>  @version.id, :edit => 'false'), notice: I18n.t('org_admin.templates.updated_message') }
		        format.json { head :no_content }
		      else
		        format.html { render action: "admin_phase" }
		        format.json { render json: @version.errors, status: :unprocessable_entity }
		      end
		    end
			end
		end

		#clone a version of a template
		def admin_cloneversion
			if user_signed_in? && current_user.is_org_admin? then
                @old_version = Version.find(params[:version_id])
				@version = @old_version.amoeba_dup
				@phase = @version.phase

		    respond_to do |format|
		      if @version.save
		        format.html { redirect_to admin_phase_dmptemplate_path(@phase, :version_id => @version.id, :edit => 'true'), notice: I18n.t('org_admin.templates.updated_message') }
		        format.json { head :no_content }
		      else
		        format.html { render action: "admin_phase" }
		        format.json { render json: @version.errors, status: :unprocessable_entity }
		      end
		    end
			end
		end

	#delete a version, sections and questions
	def admin_destroyversion
  	if user_signed_in? && current_user.is_org_admin? then
	   	@version = Version.find(params[:version_id])
	   	@phase = @version.phase
	    @version.destroy

	    respond_to do |format|

app/views/dmptemplates/_add_suggested_answer.html.erb
<!--add suggested answer. question is passed as an argument-->
<%= form_for :suggested_answer, :url => {:action => 'admin_createsuggestedanswer'} do |f| %>
	<%= f.hidden_field :organisation_id, :value => current_user.organisation.id %>
	<%= f.hidden_field :question_id, :value => question.id %>
	
	<table class="dmp_details_table phase">
		<tr>
			<td class="first_template"><%= t('org_admin.questions.suggested_or_example_answer_label')%></td>
			<td>
				<ul>
					<li><%= f.select :is_example, {t('org_admin.questions.example_answer_label') => true, t('org_admin.questions.suggested_answer_label') => false} %></li>
					<li><%= f.text_area :text, :rows => 5 %>
					</li>
				</ul>
			</td>
		</tr>
	</table>	
	<br/>
		
	<!-- submit buttons -->
	<div class="move_2_right">
		<%= f.submit t('helpers.submit.save'), :class => 'btn btn-primary' %>
		<%= link_to t('helpers.submit.cancel'), '#', :id => 'cancel_suugested_answer', :class => 'btn cancel' %>
	</div>
<%end%>

app/views/dmptemplates/_edit_section.html.erb
<!-- 
**Project: DMPonline v4
**Description: This block edits a section and its questions.
**Arguments transferred: 'section'  
**Copyright: Digital Curation Centre
-->


<%= form_for(section, :url => admin_updatesection_dmptemplate_path(section, :phase => phase, :edit => edit), :html => { :method => :put}) do |s| %>
	<%if @open && @section_id == section.id then%>
			<% toggle = 'accordion-body  section-collapse in collapse'%>
		<%else%>
			<% toggle = 'accordion-body collapse section-collapse' %>
		<%end%>

	<div class="accordion-group" >
		<div class="accordion-heading">
			<div class="div_left make_div_smaller">
				<div class="accordion_heading_text">
					<%= s.text_field :title, :as => :string, :class => 'text_field', :placeholder => t('org_admin.templates.section_title_placeholder') %>
				</div>
			</div>
			<div class="div_right make_div_longer">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#sections-accordion" href="#collapse-sec-<%= section.id %>">
					<!-- + or - icon-->
		        	<span class="icon-plus icon-white accordion-icon"> </span>
		        </a>
			</div>
		</div>


		<div id="collapse-sec-<%= section.id %>" class="<%= toggle %>" >
			<div class="accordion-inner">
				<table class="dmp_details_table">
					<tr>
						<td class="first_template"><%= t('org_admin.templates.phase_order_label') %></td>
						<td><%= s.number_field :number, :in => 1..15, :class => "number_field has-tooltip", 'data-toggle' => "tooltip", 'title' => t('org_admin.templates.section_number_help_text') %></td>
					</tr>
					<tr>
						<td class="first_template"><%= t('org_admin.templates.desc_label') %></td>
						<td class="phase_table_last_column">
							<div class="div_left_icon">
								<%= text_area_tag("section-desc-#{section.id}", section.description , class: "tinymce") %>
							</div>
							<div class="div_right_icon">
								<%= link_to( image_tag('help_button.png'), '#', :class => 'section_desc_popover', :rel => "popover", 'data-html' => "true", 'data-content' => t('org_admin.templates.section_desc_help_text_html'))%>
							</div>
						</td>
					</tr>
				</table>
				<!-- save buttons-->
				<div class="move_2_right">
					<%= s.submit t('helpers.submit.save'), :class => 'btn btn-primary' %>
					<% if !section.version.published? || phase.dmptemplate.org_type == t("helpers.org_type.funder")  then%>
						<%= link_to t("helpers.submit.delete"), admin_destroysection_dmptemplate_path(:section_id => section.id),
						:confirm => t("org_admin.templates.section_delete_message", :section_title => section.title ), :method => :delete, :class => "btn btn-primary"%>
					<%end%>
					<%= link_to t('helpers.submit.cancel'), :back, :class => 'btn cancel' %>
				</div>
			<%end%>
				<div class="two-column-clear question-divider"></div>
				<% @questions = section.questions.order("number")%>
				<%if @questions.count > 0 %>
					<% question_left = @questions.count %>
					<% @questions.each do |question| %>
                        <div class="question_guidance_block">
                            <div id="show_question_div_<%= question.id%>" class="<%= if question.id == @question_id then "current_question" end %>">
                                <!-- render the show question block-->
                                <%= render :partial => 'show_question', locals: {question: question} %>
                            </div>

                            <div id="edit_question_div_<%= question.id%>"  style="display: none">
                                <!-- render the edit question block-->
                                <%= render :partial => 'edit_question', locals: {question: question} %>
                            </div>
                        </div>
                        <!--verify how many questions are left -->
                        <%if question_left.to_i > 1 then %>
                            <div class="two-column-clear question-divider"></div>
                        <%else%>
                            <div class="two-column-clear"></div>
                        <%end%>
                        <% question_left = question_left - 1 %>
                        
					<%end%>
				<%end%>

				<!-- Add a new question if the version is not published-->
				<% if !section.version.published? || phase.dmptemplate.org_type == t("helpers.org_type.funder")  then%>
					<%if @questions.count != 0 %>
						<div class="two-column-clear question-divider"></div>
					<%end%>
					<!-- add question block -->
					<div id="add_question_block_div_<%= section.id%>" style="display: none">
						<%= render :partial => 'add_question', locals: {section: section} %>
					</div>

					<!-- add question button-->
					<div id="add_question_button_div_<%= section.id%>">
						<div class="div_left">
							<%= hidden_field_tag :section_id, section.id, :class => "section_id" %>
							<%= link_to t("org_admin.add_question_label"), '#', :class => "btn btn-primary add_question_button" %>
						</div>
					</div>
				<%end%>

				<div class="two-column-clear"></div>
			</div>
		</div>
	</div>

app/views/dmptemplates/_edit_suggested_answer.html.erb
<!--edit suggested answer. question is passed as an argument-->
<%= form_for(suggested_answer, :url => admin_updatesuggestedanswer_dmptemplate_path(suggested_answer), :html => { :method => :put}) do |f| %>
	<%= f.hidden_field :organisation_id, :value => current_user.organisation.id %>

	<table class="dmp_details_table phase">
		<tr>
			<td class="first_template"><%= t('org_admin.questions.suggested_or_example_answer_label')%></td>
			<td>
				<ul>
					<li><%= f.select :is_example, {t('org_admin.questions.example_answer_label') => true, t('org_admin.questions.suggested_answer_label') => false} %></li>
					<li><%= f.text_area :text, :rows => 5 %></li>
				</ul>
			</td>
		</tr>
	</table>
	<br/>

	<!-- submit buttons -->
	<div class="move_2_right">
		<%= f.submit t('helpers.submit.save'), :class => 'btn btn-primary' %>
		<%= link_to t("helpers.submit.delete"), admin_destroysuggestedanswer_dmptemplate_path(:suggested_answer => suggested_answer.id),
			:confirm => t("org_admin.questions.delete_suggested_answer_message", :question_text => question.text ), :method => :delete, :class => "btn btn-primary"%>
		<%= hidden_field_tag :question_id, question.id, :class => "question_id" %>
		<%= link_to t('helpers.submit.cancel'), '#', :class => 'btn cancel cancel_edit_suggested_answer' %>
	</div>
<%end%>

app/views/dmptemplates/_option_fields.html.erb
<!--Add options answers to a question-->
<tr class="options_content">
	<td class="small"><%= f.number_field :number,:in => 1..20, :class => "number_field option"%></td>
	<td class="medium"><%= f.text_field :text, :as => :string, :class => "small_text_field" %></td>
	<td class="small"><%= f.check_box :is_default %></td>	
	<td class="small"><%= f.hidden_field :_destroy %><%= link_to_function t('org_admin.remove_option_label'), "remove_object(this)"%></td>																	
</tr>

app/views/dmptemplates/_versions_table.html.erb
<%if !phase.versions.nil? then %>
	<div class="versions_display_table">	
		<h3><%= t('org_admin.templates.versions_label')%></h3>
		<p>
			<%= t('org_admin.versions.versions_text_html')%>
		</p>
		<!--table displaying versions for this phase-->
		<table class="dmp_table" id="dmp_table">
			<thead>
				<tr>
					<th><%= t('org_admin.templates.title_label')%></th>
					<th><%= t('org_admin.templates.published_label')%></th>
					<th><%= t('org_admin.templates.created')%></th>
					<th><%= t('org_admin.templates.last_updated') %></th>
					<th><%= t('org_admin.templates.actions') %></th>
				</tr>
			</thead>
			<tbody>
				<% phase.versions.each do |v|%>
					<!--Alert pop up block for version editing-->
					<div id='version_edit_alert_<%= v.id%>' data-container="body" data-id="<%= v.id%>" data-backdrop='static' class='modal hide fade'>
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
							<h3><%= t('org_admin.versions.edit_alert_label')%></h3>
						</div>
						<div class="modal-body">
							<div><p><%= t('org_admin.versions.edit_alert_text')%></p></div>
						</div>
						<div class="modal-footer">
						  	<%= link_to t('org_admin.versions.edit_versions_label'), admin_phase_dmptemplate_path( :version_id => v.id, :id => phase.id , :edit => 'true') , :id => "edit-version-confirmed", :class => "btn cancel" %>
							<%= link_to t('org_admin.versions.clone_versions_label'), admin_cloneversion_dmptemplate_path( :version_id => v.id, :phase => phase ) , :id => "clone-version-confirmed", :class => "btn btn-primary" %>
					  </div>
					</div>
					<tr>
						<td class="dmp_td_no_border">
							<%= v.title %>
						</td>
						<td class="dmp_td_border">
							<%= v.published %>
						</td>
						<td class="dmp_td_border">
							<%= l v.created_at.to_date, :formats => :short %>
						</td>
						<td class="dmp_td_border">
							<%= l v.updated_at.to_date, :formats => :short %>
						</td>  
						<td class="dmp_td_border">
							<%= link_to t("helpers.view"), admin_phase_dmptemplate_path( :version_id => v.id, :id => phase.id , :edit => 'false'), :class => "dmp_table_link"%>
							<% if v.published? then%>
								<a id="edit-version-button" data-toggle="modal" href="#version_edit_alert_<%= v.id%>" class="dmp_table_link " >
									<%= t('org_admin.versions.edit_label')%>
								</a>
                                <%= link_to t("helpers.preview"), admin_previewphase_dmptemplate_path(v), :class => "dmp_table_link" %>
							<%else%>
								<%= link_to t("org_admin.versions.edit_label"), admin_phase_dmptemplate_path(phase, :version_id => v.id, :edit => 'true'), :class => "dmp_table_link" %>
                                <%= link_to t("helpers.preview"), admin_previewphase_dmptemplate_path(v), :class => "dmp_table_link" %>
								<%#= link_to t("helpers.submit.delete"), admin_destroyversion_dmptemplate_path(:version_id => v.id, :phase => phase , :edit => 'false'),
								:confirm => t("org_admin.versions.delete_message", :version_title => v.title ), :method => :delete, :class => "dmp_table_link"%>
							<%end%>		
						</td>	
					</tr>
					
					
									
				<%end%>
			</tbody>
		</table>
	</div>



<%end%>