config/routes.rb
DMPonline4::Application.routes.draw do
  
    
  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => 'confirmations', :passwords => 'passwords', :sessions => 'sessions', :omniauth_callbacks => 'users/omniauth_callbacks'} do
  	get "/users/sign_out", :to => "devise/sessions#destroy"
  end 
  resources :contacts, :controllers => {:contacts => 'contacts'}
  
  get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  
  root :to => 'home#index'

  ActiveAdmin.routes(self)
  
  get "about_us" => 'static_pages#about_us', :as => "about_us"
  get "help" => 'static_pages#help', :as => "help"
  get "roadmap" => 'static_pages#roadmap', :as => "roadmap"
  get "terms" => 'static_pages#termsuse', :as => "terms"
  get "existing_users" => 'existing_users#index', :as => "existing_users"
  
  get "org/admin/users" => 'organisation_users#admin_index', :as => "org/admin/users"
 
 	resources :organisations, :path => 'org/admin' do
  	member do
			get 'children'
			get 'templates'
			get 'admin_show'
			get 'admin_edit'
			put 'admin_update'
		end
	end
 
 	resources :guidances, :path => 'org/admin/guidance' do
  	member do
  		get 'admin_show'
  		get 'admin_index'
			get 'admin_edit'
			get 'admin_new'
			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
			
			get 'update_phases', :as => 'update_phases'
  		get 'update_versions', :as => 'update_versions'
  		get 'update_sections', :as => 'update_sections'
  		get 'update_questions', :as => 'update_questions'
   	end
  end
 
 	resources :guidance_groups, :path => 'org/admin/guidancegroup' do
 		member do
 			get 'admin_show'
 			get 'admin_new'
 			get 'admin_edit'
 			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
  	end
  end
 
 	resource :organisation 
 
  
  resources :dmptemplates, :path => 'org/admin/templates' do
 		member do
 			get 'admin_index'
 			get 'admin_template'
			get 'admin_new'
			get 'admin_addphase'
			get 'admin_phase'
			get 'admin_previewphase'
			get 'admin_cloneversion'
			delete 'admin_destroy' 
			delete 'admin_destroyversion'
			delete 'admin_destroyphase'
			delete 'admin_destroysection'
			delete 'admin_destroyquestion'
			delete 'admin_destroysuggestedanswer'
			post 'admin_create'
			post 'admin_createphase'
			post 'admin_createsection'
			post 'admin_createquestion'
			post 'admin_createsuggestedanswer'
			put 'admin_update'
			put 'admin_updatephase'
			put 'admin_updateversion'
			put 'admin_updatesection'
			put 'admin_updatequestion'
			put 'admin_updatesuggestedanswer'
  	end
  end
   
  resources :phases
  resources :versions
  resources :sections
  resources :questions
  resources :question_themes

  
  resources :themes
  
  resources :answers
  resources :plan_sections
  resources :comments do
    member do
        put 'archive'
    end
  end
  
  resources :projects do
  	resources :plans do
		member do
			get 'status'
			get 'locked'
			get 'answer'
            get 'edit'
			post 'delete_recent_locks'
			post 'lock_section'
			post 'unlock_section'
			post 'unlock_all_sections'
			get 'export'
			get 'warning'
			get 'section_answers'
		end
	end
	
	member do
		get 'share'
		get 'export'
		post 'invite'
		post 'create'
	end
	collection do
		get 'possible_templates'
		get 'possible_guidance'
	end
  end
  
    
  resources :project_partners
  resources :project_groups

  resources :users
  resources :user_statuses
  resources :user_types
  
  resources :user_role_types
  resources :user_org_roles
  
  
  resources :organisation_types
  resources :pages
 
  resources :file_types
  resources :file_uploads

  namespace :settings do
    resource :projects
    resources :plans
  end
  

end

app/views/shared/_export_links.html.erb
<% javascript("export_configure") %>
<form method="get" action="<%= export_project_plan_path(plan.project, plan) -%>" target="_blank" id="select-form-format">
  <%= label_tag(:format, t("helpers.format")) %>
  <%= select_tag(:format, options_for_select(ExportedPlan::VALID_FORMATS, :pdf)) %>
  <input type="submit" value="<%= t("helpers.export") -%>" class="btn btn-primary" />
</form>

<div class="accordion settings-accordion" id="settings-accordion-<%= plan.id -%>">
	<div class="accordion-group">
		<div class="accordion-heading">
			<a id= "settings-toggle" class="accordion-toggle" data-toggle="collapse" data-parent="#settings-accordion-<%= plan.id -%>" href="#settings-accordion-plan-<%= plan.version.phase.id %>">
				Settings <%= plan_settings_indicator(plan) -%> <span class="plus-laranja"> </span>
			</a>
		</div>
		<div id="settings-accordion-plan-<%= plan.version.phase.id %>" class="accordion-body collapse">
			<div class="accordion-inner">
				<%= render(partial: "settings/plans/export_formatting_form", locals: { plan: plan }) %>
			</div>
		</div>
	</div>
</div>

app/views/shared/_login_form.html.erb
<%= form_for(resource, :as => "user", :url => user_session_path) do |f| %>
<ul>
	<li>
		<%= devise_error_messages! %>
	</li>
	<li>
		<%= f.email_field :email, placeholder: (t('helpers.user_name')  + ' *') , :as => :email%>
	</li>
	<li>
		<%= f.password_field :password, placeholder: (t('helpers.password') + ' *'), :as => :password %>
	</li>
	<li class="forgot_password_link">
		<%= link_to t('helpers.forgot_password'), new_password_path('user'), :class => "a-orange" %>
	</li>
	<li class="remember_me_li">
		<%= f.check_box :remember_me %><%= f.label :remember_me, :class => "remember_div" do %>
			<%= t('helpers.remember_me') %>
		<%end%>
	</li>
	<li>
		<%= f.submit t('helpers.sign_in'), :class => "btn btn-primary" %>
	</li>
    <% if Rails.application.config.shibboleth_enabled %>
        <% if request.fullpath != "/users/sign_up?nosplash=true" && session[:shibboleth_data].nil? then%>
            <li>
                <div class="institution_login_link">
                    <%= link_to t('helpers.institution_sign_in_link'), user_omniauth_shibboleth_path, :class => "a-orange" %>
                    <%= t('helpers.institution_sign_in')%>
                </div>
            </li>
        <%else%>
            <%= f.hidden_field :shibboleth_id, :value => session[:shibboleth_data][:uid] %>
        <%end%> 
    <% end %>
</ul>
<% end %>

app/views/shared/_register_form.html.erb
<%= form_for(resource, :as => "user", :url => registration_path("user"),  :htmlb => {:autocomplete =>"off"}) do |f| %>
  <ul>
	<li>
		<%= devise_error_messages! %>
	</li>
	<li>
		<%= f.email_field :email, placeholder: (t('helpers.email') + ' *'), :required => true, :as => :email, :class => 'text_field has-tooltip reg-input', 'data-toggle' => "tooltip", 'data-container' => "body", 'title' => "This must be a valid email address - a message will be sent to it for confirmation." %>
		<div class="alert alert-error" style="display:none">
			<strong><%= t('helpers.error')%></strong> <%= t('helpers.valid_email')%>
		</div>
	</li>
	<% if extended then %>
		<% unless session[:shibboleth_data].nil? %>
			<%= f.hidden_field :shibboleth_id, :value => session[:shibboleth_data][:uid] %>
		<% end %>
		<li>
			<%= f.text_field :firstname, placeholder: t('helpers.first_name'), :as => :string, :class => 'text_field' %>
		</li>
		<li>
			<%= f.text_field :surname, placeholder: t('helpers.last_name'), :as => :string, :class => 'text_field' %>
		</li>
	<% end %>
	<li>
		<%= collection_select(:user, :organisation_id, Organisation.where("parent_id IS NULL").order("sort_name ASC, name ASC"), :id, :name, {include_blank: t('helpers.org_type.organisation')}, { :class => 'typeahead org_sign_up' }) %>
	</li>
  <div id="other-org-link"><a href="#"><%= t("helpers.org_not_listed") %></a></div>
	<% other_organisations = Array.new %>
	<% Organisation.where("parent_id IS ? AND is_other = ?", nil, 1).each do |org| %>
		<% other_organisations << org.id %>
	<% end %>
	<li id="other-organisation-name" style="display:none" data-orgs="<%= other_organisations.join(',') %>">
		<%= f.text_field :other_organisation, placeholder: (t('helpers.org_type.org_name') + ' *'), :as => :string , :autocomplete => "off", :class => 'text_field has-tooltip reg-input', 'data-toggle' => "tooltip", 'data-container' => "body", 'title' => "Please enter the name of your organisation." %>
	</li>
	<li>
		<%= f.password_field :password, placeholder: (t('helpers.password') + ' *'), :autocomplete => "off", :required => true, :as => :password, :class => 'text_field has-tooltip reg-input', 'data-toggle' => "tooltip", 'data-container' => "body", 'title' => "This must be at least 8 characters long." %>
		<div class="alert alert-error" style="display:none">
			<strong><%= t('helpers.error')%></strong> <%= t('helpers.password_too_small')%>
		</div>
	</li>
	<li>
		<%= f.password_field :password_confirmation, placeholder: (t('helpers.password_conf') + ' *'), :required => true, :as => :password, :class => 'text_field has-tooltip reg-input', 'data-toggle' => "tooltip", 'data-container' => "body", 'title' => "This must match what you entered in the previous field." %>
		<div class="alert alert-error" style="display:none">
			<strong><%= t('helpers.error')%></strong>&nbsp;<%= t('helpers.password_no_match')%>
		</div>
	</li>
	<li class="remember_me_li">
		<%= f.check_box :accept_terms, :required => true %> <%= f.label :accept_terms, :class => "remember_div"  do %>
		  <%= raw t('helpers.accept_terms_html')%>
		<%end%>
	</li>
	<li>
		<%= f.submit t('helpers.sign_up'), :class => "btn btn-primary" %>
	</li>
</ul>
<% end %>