config/routes.rb
DMPonline4::Application.routes.draw do
  
    
  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => 'confirmations', :passwords => 'passwords', :sessions => 'sessions', :omniauth_callbacks => 'users/omniauth_callbacks'} do
  	get "/users/sign_out", :to => "devise/sessions#destroy"
  end 
  resources :contacts, :controllers => {:contacts => 'contacts'}
  
  get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  
  root :to => 'home#index'

  ActiveAdmin.routes(self)
  
  get "about_us" => 'static_pages#about_us', :as => "about_us"
  get "help" => 'static_pages#help', :as => "help"
  get "roadmap" => 'static_pages#roadmap', :as => "roadmap"
  get "terms" => 'static_pages#termsuse', :as => "terms"
  get "existing_users" => 'existing_users#index', :as => "existing_users"
  
  get "org/admin/users" => 'organisation_users#admin_index', :as => "org/admin/users"
 
 	resources :organisations, :path => 'org/admin' do
  	member do
			get 'children'
			get 'templates'
			get 'admin_show'
			get 'admin_edit'
			put 'admin_update'
		end
	end
 
 	resources :guidances, :path => 'org/admin/guidance' do
  	member do
  		get 'admin_show'
  		get 'admin_index'
			get 'admin_edit'
			get 'admin_new'
			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
			
			get 'update_phases', :as => 'update_phases'
  		get 'update_versions', :as => 'update_versions'
  		get 'update_sections', :as => 'update_sections'
  		get 'update_questions', :as => 'update_questions'
   	end
  end
 
 	resources :guidance_groups, :path => 'org/admin/guidancegroup' do
 		member do
 			get 'admin_show'
 			get 'admin_new'
 			get 'admin_edit'
 			delete 'admin_destroy' 
			post 'admin_create'
			put 'admin_update'
  	end
  end
 
 	resource :organisation 
 
  
  resources :dmptemplates, :path => 'org/admin/templates' do
 		member do
 			get 'admin_index'
 			get 'admin_template'
			get 'admin_new'
			get 'admin_addphase'
			get 'admin_phase'
			get 'admin_previewphase'
			get 'admin_cloneversion'
			delete 'admin_destroy' 
			delete 'admin_destroyversion'
			delete 'admin_destroyphase'
			delete 'admin_destroysection'
			delete 'admin_destroyquestion'
			delete 'admin_destroysuggestedanswer'
			post 'admin_create'
			post 'admin_createphase'
			post 'admin_createsection'
			post 'admin_createquestion'
			post 'admin_createsuggestedanswer'
			put 'admin_update'
			put 'admin_updatephase'
			put 'admin_updateversion'
			put 'admin_updatesection'
			put 'admin_updatequestion'
			put 'admin_updatesuggestedanswer'
  	end
  end
   
  resources :phases
  resources :versions
  resources :sections
  resources :questions
  resources :question_themes

  
  resources :themes
  
  resources :answers
  resources :plan_sections
  resources :comments do
    member do
        put 'archive'
    end
  end
  
  resources :projects do
  	resources :plans do
		member do
			get 'status'
			get 'locked'
			get 'answer'
            get 'edit'
			post 'delete_recent_locks'
			post 'lock_section'
			post 'unlock_section'
			post 'unlock_all_sections'
			get 'export'
			get 'warning'
			get 'section_answers'
		end
	end
	
	member do
		get 'share'
		get 'export'
		post 'invite'
		post 'create'
	end
	collection do
		get 'possible_templates'
		get 'possible_guidance'
	end
  end
  
    
  resources :project_partners
  resources :project_groups

  resources :users
  resources :user_statuses
  resources :user_types
  
  resources :user_role_types
  resources :user_org_roles
  
  
  resources :organisation_types
  resources :pages
 
  resources :file_types
  resources :file_uploads

  namespace :settings do
    resource :projects
    resources :plans
  end
  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :get_plan_list_columns, only: %i( index )

	# GET /projects
	# GET /projects.json
	def index
		if user_signed_in? then
			if (current_user.shibboleth_id.nil? || current_user.shibboleth_id.length == 0) && !cookies[:show_shib_link].nil? && cookies[:show_shib_link] == "show_shib_link" then
				flash.notice = "Would you like to #{view_context.link_to 'link your DMPonline account to your institutional credentials?', user_omniauth_shibboleth_path}".html_safe
			end

			@projects = current_user.projects.filter(params[:filter])
			@has_projects = current_user.projects.any? # unfiltered count

			respond_to do |format|
				format.html # index.html.erb
				format.json { render json: @projects }
			end
		else
			respond_to do |format|
				format.html { redirect_to edit_user_registration_path }
			end
		end
	end

	# GET /projects/1
	# GET /projects/1.json
	def show
		@project = Project.find(params[:id])
		@show_form = false
		if params[:show_form] == "yes" then
			@show_form = true
		end
		if user_signed_in? && @project.readable_by(current_user.id) then
			respond_to do |format|
				format.html # show.html.erb
				format.json { render json: @project }
			end
		elsif user_signed_in? then
			respond_to do |format|
				format.html { redirect_to projects_url, notice: "This account does not have access to that plan." }
			end
		else
			respond_to do |format|
				format.html { redirect_to edit_user_registration_path }
			end
		end
	end

	# GET /projects/new
	# GET /projects/new.json
	def new
		if user_signed_in? then
			@project = Project.new
			@project.organisation = current_user.organisation
			@funders = orgs_of_type(t('helpers.org_type.funder'), true)
			@institutions = orgs_of_type(t('helpers.org_type.institution'))
			respond_to do |format|
			  format.html # new.html.erb
			  format.json { render json: @project }
			end
		else
			respond_to do |format|
				format.html { redirect_to edit_user_registration_path }
			end
		end
	end

	# GET /projects/1/edit
     # Should this be removed?
	def edit
		@project = Project.find(params[:id])
		if !user_signed_in? then
               respond_to do |format|
				format.html { redirect_to edit_user_registration_path }
			end
		elsif !@project.editable_by(current_user.id) then
			respond_to do |format|
				format.html { redirect_to projects_url, notice: "This account does not have access to that plan." }
			end
		end
	end

	def share
		@project = Project.find(params[:id])
		if !user_signed_in? then
               respond_to do |format|
				format.html { redirect_to edit_user_registration_path }
			end
		elsif !@project.editable_by(current_user.id) then
			respond_to do |format|
				format.html { redirect_to projects_url, notice: "This account does not have access to that plan." }
			end
		end
	end

	def export
		@project = Project.find(params[:id])
		if !user_signed_in? then
               respond_to do |format|
				format.html { redirect_to edit_user_registration_path }
			end
		else 
			respond_to do |format|
				format.html { render action: "export" }
                
			end
		end
	end

	# POST /projects
	# POST /projects.json
	def create
    	if user_signed_in? then
			@project = Project.new(params[:project])
			if @project.dmptemplate.nil? && params[:project][:funder_id] != "" then # this shouldn't be necessary - see setter for funder_id in project.rb
				funder = Organisation.find(params[:project][:funder_id])
				if funder.dmptemplates.count == 1 then
					@project.dmptemplate = funder.published_templates.first
				end
			elsif @project.dmptemplate.nil? || params[:default_tag] == 'true' then
				if @project.organisation.nil?  || params[:default_tag] == 'true'  || @project.organisation.published_templates.first.nil? then
					@project.dmptemplate = Dmptemplate.find_by_is_default(true)
				else
					@project.dmptemplate = @project.organisation.published_templates.first
				end
			end
			@project.principal_investigator = current_user.name(false)
			@project.title = I18n.t('helpers.project.my_project_name')+' ('+@project.dmptemplate.title+')'
			@project.assign_creator(current_user.id)
			respond_to do |format|
				if @project.save
					format.html { redirect_to({:action => "show", :id => @project.slug, :show_form => "yes"}, {:notice => I18n.t('helpers.project.success')}) }
					format.json { render json: @project, status: :created, location: @project }
				else
					format.html { render action: "new" }
					format.json { render json: @project.errors, status: :unprocessable_entity }
				end
			end
		else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
	end

	# PUT /projects/1
	# PUT /projects/1.json
	def update
		@project = Project.find(params[:id])
		if user_signed_in? && @project.editable_by(current_user.id) then
			respond_to do |format|
				if @project.update_attributes(params[:project])
					format.html { redirect_to @project, notice: 'Project was successfully updated.' }
					format.json { head :no_content }
				else
					format.html { render action: "edit" }
					format.json { render json: @project.errors, status: :unprocessable_entity }
				end
			end
		else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
	end

	# DELETE /projects/1
	# DELETE /projects/1.json
	def destroy
		@project = Project.find(params[:id])
		if user_signed_in? && @project.editable_by(current_user.id) then
			@project.destroy

			respond_to do |format|
				format.html { redirect_to projects_url }
				format.json { head :no_content }
			end
		else
			render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
		end
	end

	# GET /projects/possible_templates.json
	def possible_templates
		if !params[:funder].nil? && params[:funder] != "" && params[:funder] != "undefined" then
			funder = Organisation.find(params[:funder])
		else
			funder = nil
		end
		if !params[:institution].nil? && params[:institution] != "" && params[:institution] != "undefined" then
			institution = Organisation.find(params[:institution])
		else
			institution = nil
		end
		templates = {}
		unless funder.nil? then
			funder.published_templates.each do |t|
				templates[t.id] = t.title
			end
		end
		if templates.count == 0 && !institution.nil? then
			institution.published_templates.each do |t|
				templates[t.id] = t.title
			end
			institution.children.each do |o|
				o.published_templates.each do |t|
					templates[t.id] = t.title
				end
			end
		end
		respond_to do |format|
			format.json { render json: templates.to_json }
		end
	end

	def possible_guidance
		if !params[:template].nil? && params[:template] != "" && params[:template] != "undefined" then
			template = Dmptemplate.find(params[:template])
		else
			template = nil
		end
		if !params[:institution].nil? && params[:institution] != "" && params[:institution] != "undefined" then
			institution = Organisation.find(params[:institution])
		else
			institution = nil
		end
		excluded_orgs = orgs_of_type(t('helpers.org_type.funder')) + orgs_of_type(t('helpers.org_type.institution')) + Organisation.orgs_with_parent_of_type(t('helpers.org_type.institution'))
		guidance_groups = {}
		ggs = GuidanceGroup.guidance_groups_excluding(excluded_orgs) 
	
		ggs.each do |gg|
			guidance_groups[gg.id] = gg.name
		end
        
        #subset guidance that belong to the institution
		unless institution.nil? then
			optional_gg = GuidanceGroup.where("optional_subset =  ? && organisation_id = ?", true, institution.id)
			optional_gg.each do|optional|
				guidance_groups[optional.id] = optional.name
			end
			
			institution.children.each do |o|
				o.guidance_groups.each do |gg|
					include = false
					gg.guidances.each do |g|
						if g.dmptemplate.nil? || g.dmptemplate_id == template.id then
							include = true
							break
						end
					end
					if include then
						guidance_groups[gg.id] = gg.name
					end
				end
			end
		end
        
        #If template belongs to a funder and that funder has subset guidance display then.
        if !template.nil? && template.organisation.organisation_type.name == t('helpers.org_type.funder') then
            optional_gg = GuidanceGroup.where("optional_subset =  ? && organisation_id = ?", true, template.organisation_id)
			optional_gg.each do|optional|
				guidance_groups[optional.id] = optional.name
			end
        end
        
        
		respond_to do |format|
			format.json { render json: guidance_groups.to_json }
		end
	end
	
	private

	def orgs_of_type(org_type_name, published_templates = false)
		org_type = OrganisationType.find_by_name(org_type_name)
		all_such_orgs = org_type.organisations
		if published_templates then
			with_published = Array.new
			all_such_orgs.each do |o|
				if o.published_templates.count > 0 then
					with_published << o
				end
			end
			return with_published.sort_by {|o| [o.sort_name, o.name] }
		else
			return all_such_orgs.sort_by {|o| [o.sort_name, o.name] }
		end
	end
end

app/controllers/settings/projects_controller.rb
module Settings
  class ProjectsController < SettingsController

    before_filter :get_plan_list_columns
    before_filter :get_settings

    def show
      respond_to do |format|
        format.html
        format.json { render json: settings_json }
      end
    end

    def update
      columns = (params[:columns] || {}).keys.map(&:intern)

      if @settings.update_attributes(columns: columns)
        respond_to do |format|
          format.html { redirect_to(projects_path) }
          format.json { render json: settings_json }
        end
      else
        render(action: :show) # Expect #show to display errors etc
      end
    end

  private

    def get_settings
      @settings = current_user.settings(:plan_list)
      # :name column should always be present (displayed as a disabled checkbox)
      # so it's not necessary to include it in the list here
      @all_columns -= [:name]
    end

    def settings_json
      @settings_json ||= { selected_columns: @settings.columns, all_columns: @all_columns }.to_json
    end
  end
end

app/views/projects/_dropdowns_new_project.html.erb
<!-- Create a new project (3 dropdowns = 6 options) -->
<%= semantic_form_for @project, :url => {:controller => :projects, :action => :create }, :html=>{:method=>:post} do |f| %>
	<%= f.inputs do %>
        <%= hidden_field_tag :default_tag, "false" ,:id => "default_tag" %>
		<div class="createa-project">
			<h1> <%= t('helpers.project.create_page.title')%> </h1>
			<div class="info-new-project">
				<p><%= raw t('helpers.project.create_page.desc_html')%></p>

			</div>
			<div class="dropdowns">
				<div class="control-group" id="funder-control-group">
					<div class="controls">
						<%= f.input :funder_id, :as => :select, :collection => @funders, :label => t('helpers.project.create_page.funders_question'), :input_html => { :multiple => false, :class => "typeahead" }, :include_blank =>  t('helpers.org_type.funder') %>
						<div class="div_clear"></div>
						<div id="other-funder-link" class="move_2_right">
							<a href='#' id="no-funder"><%= t('helpers.project.not_applicable')%></a>
						</div>
						<div class="create_project_question_descriptions">
							<%= t('helpers.project.create_page.funders_question_description')%>
						</div>
					</div>
					<div class="div_clear"></div>
					<div id="other-funder-name" class="controls" style="display:none;">
						<%= f.input :funder_name, :as => :string, :placeholder => t('helpers.project.funder_name'), :label => t('helpers.project.create_page.other_funder_name_label') %>
					</div>
				</div>
				<div class="control-group" id="institution-control-group">
					<div class="controls">
						<%= f.input :institution_id, :as => :select, :collection => @institutions, :label => t('helpers.project.create_page.institution_question'), :input_html => { :multiple => false, :class => "typeahead" }, :include_blank =>  t('helpers.org_type.organisation')  %>
						<div class="div_clear"></div>
						<div class="move_2_right">
							<a href='#' id="no-institution"><%= t('helpers.project.not_applicable')%></a>
						</div>
						<div class="create_project_question_descriptions">
							<%= t('helpers.project.create_page.institution_question_description')%>
						</div>
					</div>
				</div>
				<div class="control-group" id="template-control-group">
					<div class="controls">
						<%= f.input :dmptemplate, :as => :select, :collection => Dmptemplate.find_all_by_published(1), :label => "Choose a template", :input_html => { :multiple => false, :class => "typeahead" } %>
						<div class="create_project_question_descriptions">
							<%= t('helpers.project.multi_templates') %>
						</div>
					</div>
				</div>
				<div class="control-group" id="guidance-control-group">
					<div class="controls">
						<% other_guidance = GuidanceGroup.all %>
						<%= f.input :guidance_groups, :as => :check_boxes, :collection => other_guidance, :label => t("helpers.project.create_page.other_guidance_question"), :member_label => :display_name %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	<!-- submit buttons -->
	<%= f.actions do %>
		<a id="create-plan-button" style="display:none;" data-toggle="modal" href="#project-confirmation-dialog" class="btn btn-primary"><%= t('helpers.project.create')%></a>
	<% end %>
<% end %>

app/views/projects/_form.html.erb
<div class="project-details-body">
	<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
		<div class="field-group">
			<%= f.label t('helpers.title'), :class => 'left-label' %>
			<div class="left-field">
				<%= f.text_field :title, :class => 'text_field has-tooltip', 'data-toggle' => "tooltip", 'title' => t('helpers.project.project_name_help_text') %>
			</div>
		</div>
		<div class="field-group">
			<%= f.label  t('helpers.project.grant_title'), :class => 'left-label' %>
			<div class="left-field">
				<%= f.text_field :grant_number, :class => 'text_field has-tooltip', 'data-toggle' => "tooltip", 'title' => t('helpers.project.grant_help_text') %>
			</div>
		</div>
		<div class="field-group">
			<%= f.label t('helpers.note'), :class => 'left-label' %>
			<div class="left-field">
				<%= f.text_area :note, :class => 'text_area', :rows => 10 %>
			</div>
		</div>
		<div class="form-actions">
			<%= f.submit t("helpers.submit.save"), :class => 'btn btn-primary' %>
			<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
									projects_path, :class => 'btn' %>
		</div>
	<% end %>
</div>

app/views/projects/_project_list_head.html.erb
<tr>
  <% @selected_columns.each do |column| %>
    <%= project_list_head(column) %>
  <% end %>
  <th class="dmp_th_medium"><%= t('helpers.select_action')%> </th>
</tr>

app/views/projects/_project_list_item.html.erb
<tr>
  <% @selected_columns.each do |column| %>
    <%= project_list_body(column, project) %>
  <% end %>
  <td class="dmp_td_medium">
    <% if project.editable_by(current_user.id) then %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")), project_path(project), :class => "dmp_table_link"%>

      <% if project.administerable_by(current_user.id) then %>
        <%= link_to t("helpers.project.share.tab_share"), project_path([project, "share"]), :class => "dmp_table_link"%>
      <% end %>

      <%= link_to t("helpers.project.tab_export"), project_path([project, "export"]), :class => "dmp_table_link"%>

      <% if project.administerable_by(current_user.id) then %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project), :class => "dmp_table_link",
          :method => :delete, :data => {
            :confirm => t("helpers.project.confirm_delete_text")
          }%>
      <% end %>
    <% else %>
      <%= link_to t(".view", :default => t("helpers.view")), project_path(project), :class => "dmp_table_link"%>
      <%= link_to t("helpers.project.tab_export"), project_path([project, "export"]), :class => "dmp_table_link"%>
    <% end %>

  </td>
</tr>

app/views/projects/_project_nav_tabs.html.erb
<!-- project navigation -->  
<div id="project-tabs" class="nav-project-tabs">
	<ul class="nav nav-tabs" data-tabs="tabs">
		<!-- Project details (views/projects/_project_details.html.erb)-->
		<% if active == "show_project" then %>
			<li class="active">
		<% else %>
			<li>
		<% end %>
		<%= link_to t("helpers.project.tab_plan"), project %>
	   		</li>
    <!-- Plans (phases)-->
    <% project.plans.each do |plan| %>
		<% if active == plan.id then %>
			<li class="active">
		<% else %>
			<li>
		<% end %>
		<% if active == "show_project" || active == "share_project" || active == "export_page" then %>
			<%= link_to plan.version.phase.title, [:edit, @project, plan]%>
		<% else %>
			<%= link_to plan.version.phase.title, [:edit, @plan.project, plan]%>
		<% end %>   
		</li>
    <% end %>
    <!--Share project (project admin only)-->
    <% if project.administerable_by(current_user.id) then %>
		<% if active == "share_project" then %>
			<li class="active">
		<% else %>
			<li>
		<% end %>
		<%= link_to t('helpers.project.share.tab_share'), ["share", project] %>
		</li>
	<% end %>
	<!-- Export page that display all plans options to export-->
		<% if active == "export_page" then %>
			<li class="active">
		<% else %>
			<li>
		<% end %>
		<%= link_to t('helpers.project.tab_export'), ["export",project] %>
	   		</li>
	</ul>
</div>

app/views/projects/_project_title.html.erb
<!-- Project title -->
<div class="project-title-container">
    <div class="project-title">
        <h2>
            <%= project.title %>
        </h2> 
    </div>
</div>

app/views/projects/_toolbar.html.erb
<div class="dmp_toolbar">
  <form action="<%= projects_path -%>" method="get" id="filter_form">
    <%= search_field_tag(:filter, params[:filter], placeholder: t('helpers.project.filter.placeholder')) %>
    <a id="clear_filter" class="icon-remove" href="<%= projects_path -%>" title="<%= t('helpers.project.filter.cancel') -%>">
      <span class="hide-text"><%= t('helpers.project.filter.cancel') -%></span>
    </a>
    <input type="submit" class="btn btn-primary" value="<%= t('helpers.project.filter.submit') -%>" />
  </form>
  <a id="toolbar_configure" class="btn-configure" href="<%= settings_projects_path -%>" title="<%= t('helpers.project.configure') -%>">
    <i class="icon-cog"></i>
  </a>
</div>

app/views/projects/edit.html.erb
<%- model_class = Project -%>

<!-- render the project title -->
<%= render :partial => "/projects/project_title", locals: {project: @project} %>

<!-- render navigation tabs for the project-->
<%= render :partial => "project_nav_tabs", locals: {project: @project, active: "edit_project"} %>

<%= render :partial => 'form' %>

app/views/projects/export.html.erb
<%- model_class = Project -%>

<!-- render the project title -->
<%= render :partial => "/projects/project_title", locals: {project: @project} %>

<!-- render navigation tabs for the project-->
<%= render :partial => "project_nav_tabs", locals: {project: @project, active: "export_page"} %>

<!-- main info to export -->
<div class="dmp_details_body">
	<!--Text describing page content-->
	<%= raw t('helpers.project.export_text_html')%>
	
	<!-- If project has plans-->
	<% if @project.plans.any? %>
		<% if @project.plans.count == 1 then %>
			<% @project.plans.each do |plan| %>
				<%= render :partial => "/shared/export_links", locals: {plan: plan} %>
			<% end %>
		<%else%>	
			<% @project.plans.each do |plan| %>
				<div class="accordion" id="project-accordion">
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#project-accordion" href="#<%= plan.version.phase.id %>">
								<h3><%= plan.version.phase.title %><span class="plus-laranja"> </span>
								</h3>
							</a>
						</div>
						<div id="<%= plan.version.phase.id %>" class="accordion-project collapse">
							<div class="accordion-inner">
								<%= render :partial => "/shared/export_links", locals: {plan: plan} %>
							</div>
						</div>
					</div>
				</div>				
			<%end%>	
		<%end%>		
	<%end%>	
	
</div>						

app/views/projects/index.html.erb
<%- model_class = Project -%>
<% javascript 'toolbar.js' %>
<h1>
	<%= t('helpers.project.projects_title') %>
</h1>

<!-- if the user has projects -->
<% if @has_projects %>

	<p>
		<%= raw t('helpers.project.project_text_when_project')%>
	</p>
    
	<%= render(partial: 'toolbar') %>
	<table id="dmp_table" class="dmp_table tablesorter">
	  <thead>
	    <%= render(partial: "project_list_head") %>
	  </thead>
	  <tbody>
	    <% if @projects.any? %>
	      <% @projects.each do |project| %>
	        <%= render(partial: "project_list_item", locals: { project: project } ) %>
	      <% end %>
	    <% else %>
	      <tr><td colspan="<%= @selected_columns.length -%>"><%= t("helpers.project.filter.no_matches", filter: params[:filter]) %><td></tr>
	    <% end %>
	  </tbody>
	</table>
	<% if current_user.dmponline3 then %>
		<p>You can view or edit earlier plans by visiting <%= link_to("the previous version of DMPonline", "http://dmponline3.dcc.ac.uk") %>.</p>
	<% end %>
<!-- if the user does not have projects -->
<% else %>
	<p>
		<%= raw t("helpers.project.project_text_when_no_project")%>
	</p>

<% end %>

<!-- link button to create a new project -->
<p>
	<%= link_to t('.new', :default => t("helpers.project.create")),
            new_project_path,
            :class => 'btn btn-primary' %>
</p>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<% javascript 'projects.js' %>
<div class="new-project-container">
        <!-- render dropdowns for plan selection -->
    <%= render "dropdowns_new_project" %>

</div>
<div id='project-confirmation-dialog' data-container="body" data-backdrop='static' class='modal hide fade'>
	<div class="modal-header">
		<h3><%= t('helpers.project.confirmation_text')%></h3>
		<p><%= raw t('helpers.project.confirmation_text_desc')%></p>
	</div>
	<div class="modal-body">
		<div><p><%= t('helpers.org_type.funder')%>: <span id="confirm-funder"><%= t('helpers.none')%></span></p></div>
		<div><p><%= t('helpers.org_type.institution')%>: <span id="confirm-institution"><%= @project.organisation.nil? ? t('helpers.none') : @project.organisation %></span></p></div>
		<div style="display:none"><p><%= t('helpers.org_type.template')%>: <span id="confirm-template"></span></p></div>
		<div><p><%= t('helpers.org_type.other_guidance')%>: <ul id="confirm-guidance"></ul></p></div>
	</div>
	<div class="modal-footer">
    <a href="#" id="new-project-cancelled" class="btn"><%= t('helpers.submit.cancel')%></a>
    <a href="#" id="new-project-confirmed" class="btn btn-primary"><%= t('helpers.project.confirmation_button_text')%></a>
  </div>
</div>

<!-- alert for the default template-->
<div id='default-template-confirmation-dialog' data-container="body" data-backdrop='static' class='modal hide fade'>
	<div class="modal-header">
		<h3><%= t('helpers.project.confirmation_text')%></h3>
	</div>
	<div class="modal-body">
		<div><p><%= raw t('helpers.project.default_confirmation_text_desc')%></p></div>
		<!-- verify if the current user organisation has or a template or guidance. if true display alert text-->
		<%if !Dmptemplate.own_institutional_templates(current_user.organisation_id).empty? then %>
			<div><p><strong><%= raw t('helpers.project.alert_default_template_text_html', :org_name => current_user.organisation.name )%></strong></p></div>
		<%end%>	
	</div>
	<div class="modal-footer">
    	<a href="#" id="default-template-cancelled" class="btn"><%= t('helpers.submit.cancel')%></a>
    	<a href="#" id="default-template-confirmed" class="btn btn-primary"><%= t('helpers.project.default_confirmation_button_text')%></a>
  	</div>
</div>

app/views/projects/show.html.erb
<%- model_class = Project -%>

<!-- render the project title -->
<%= render :partial => "/projects/project_title", locals: {project: @project} %>

<!-- render navigation tabs for the project-->
<%= render :partial => "project_nav_tabs", locals: {project: @project, active: "show_project"} %>

<!-- project details -->
<%= render "project_details" %>